services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/web.Dockerfile
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./public:/var/www/html
      - ./vendor:/var/www/vendor

  db:
    build:
      context: .
      dockerfile: dockerfiles/db.Dockerfile
    ports:
      - "3306:3306"


    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db

volumes:
  mysql_data:
